/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      label: 'Welcome to Coalesce',
      id: 'intro'
    },
    {
      type: 'category',
      label: 'Getting Started',
      link:{
        type: 'generated-index',
        title: 'This is a generated index example',
        description: 'Some description',
        
      },
      items: [
        'getting-started/quick-start'
      ]
    },
    {
      type: 'category',
      label: 'Setup Your Project',
      items: [
        {
          type: 'category',
          label: 'Connecting to Snowflake',
          items: [
            'setup-your-project/connecting-to-snowflake/snowflake-oauth'
          ]
        },
        'setup-your-project/projects'
      ]
    }
  ],
  apiSidebar: [{type: 'autogenerated', dirName: 'api'}],

};

export default sidebars;